### ISSUE TITLE
Sketch 45 (43475) doesn't seem to utilize SVGO Compressor plugin when exporting SVGs

### ISSUE THREAD

**Issue by cbobbett** [BohemianCoding/svgo-compressor#21] opened 2017-06-28 16:42 UTC
![quickbid-ui__git_](https://user-images.githubusercontent.com/291682/27649258-d8ac69f8-5bf6-11e7-9064-5fab54043c30.png)

**Comment by mischugo** [comment] 2017-07-12 09:53
Have tried the plug in and the feature on the [svgomg-website](https://jakearchibald.github.io/svgomg/)
My source is a 12kb file
- 11kb with the plug in
- 4kb with the compression on the website

**Comment by FransTwisk** [comment] 2017-07-17 12:42
Yup, seems broken in Sketch 45. Hope this will be fixed soon!

**Comment by bomberstudios** [comment] 2017-07-27 10:03
The plugin seems to be working fine here, could you please share more info about your setup? Plugin version, contents of `svgo.json` file, steps to reproduce, source files…

**Comment by mischugo** [comment] 2017-07-27 14:06
Ohhhh,

i have had to install the plug in again, because ot it's results.

Here again the result, but meanwhile with the latest version of SketchApp

Thanks


Ale Muñoz <notifications@github.com> schrieb am Do., 27. Juli 2017 um
12:03 Uhr:

**Comment by cbobbett** [comment] 2017-07-27 14:53
I reinstalled the SVGO compressor for Sketch 45.2 (43514).

Right click on the SVG icon in Sketch gives me this:
https://gist.github.com/cbobbett/66b83146028ece368e7ecbf932842467

SVGO Compressor export gives me this:
https://gist.github.com/cbobbett/eb96fd426c67fc4c91609459cace3885

svgo.json:
https://gist.github.com/cbobbett/bb7a8322643f1a3aeb07904deaa6e0b2

Source file:
[file-document.svg.zip](https://github.com/BohemianCoding/svgo-compressor/files/1180334/file-document.svg.zip)

Also, in Sketch:
_Plugins_ > _SVGO Compressor_ > _About SVGO Compressor_ does nothing. 
Used to open a window which could lead to config settings if I remember correctly.

**Comment by bomberstudios** [comment] 2017-07-27 16:48
Are you, by any chance, using High Sierra?

**Comment by cbobbett** [comment] 2017-07-27 16:49
I'm using Sierra, 10.12.6.

**Comment by bomberstudios** [comment] 2017-07-27 16:54
ah, it looks like your `svgo.json` file has invalid syntax. Remove it and everything should work fine.

**Comment by thierryc** [comment] 2017-07-27 16:57
Or close the last params 

```
…
   "params": {
        "attrs": "fill"
    }
}
```

**Comment by mischugo** [comment] 2017-07-28 09:37
I am wondering. I don't have the described parameter in svg.json

See attached file


Thierry Charbonnel <notifications@github.com> schrieb am Do., 27. Juli 2017
um 18:57 Uhr:

**Closed** 2017-07-28 10:04 UTC

**Comment by cbobbett** [comment] 2017-07-30 19:53
Removing the svgo.json file resolved the issue. Thanks!

**Comment by bomberstudios** [comment] 2017-07-31 07:53
🎉

**Comment by bomberstudios** [comment] 2017-07-31 07:53
I'll see if I can add some kind of check for JSON validity, and improve error reporting, thanks for the report!
